### users index
GET http://localhost:3000/users

### users create
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Lilly Lemon",
  "username": "lilemon",
  "bio": "Whatsup squad fam",
  "email": "lilemon@example.com"
}

### users show
GET http://localhost:3000/users/6

### users update
PATCH http://localhost:3000/users/7
Content-Type: application/json

{
  "name": "Lilleth Lemon"
}

### users delete
DELETE http://localhost:3000/users/7